Feat/login page design
ticketland-io/user-mobile-app pull request #3
Opened 2023-01-18 12:42 UTC by GeorgeNiotis

![image](https://user-images.githubusercontent.com/61066354/213174167-1dc09d85-e948-461a-bfef-232d205982f5.png)

2023-01-18 12:54 UTC, antonispoulakis requested changes

2023-01-18 12:54 UTC, antonispoulakis commented on src/view/components/Shadow/index.jsx
> +  const classes = styles()
since we don't have `class` or `className` in react-native, you can change the naming convention to

```
import useStyle from './styles'

const Shadow = props => {
  const styles = useStyles()
}
```

2023-01-18 12:54 UTC, antonispoulakis commented on src/view/components/Shadow/styles.js
> +    // border: '1 solid',
dont commit comments

2023-01-18 12:54 UTC, antonispoulakis commented on src/view/core/Router.jsx
>    const classes = styles()
same here, apply this everywhere

2023-01-18 12:54 UTC, antonispoulakis commented on src/view/core/theme.jsx
> +    Text: (prop) => ({
can you explain the difference between these?

2023-01-18 12:54 UTC, antonispoulakis commented on src/view/core/theme.jsx
> +        }),
this doesn't look very good; isn't there a better way to differentiate between the variants?

2023-01-18 14:33 UTC, GeorgeNiotis commented on src/view/core/theme.jsx
> +        }),
its the only way i found in order to add custom variants

2023-01-18 15:05 UTC, GeorgeNiotis commented on src/view/core/theme.jsx
> +    Text: (prop) => ({
my bad thats wrong

2023-01-20 10:29 UTC, antonispoulakis commented on src/view/pages/Splash/index.jsx
> +    }else{
please fix your styles, you can see what code you're commiting before doing the commit. You can't have these mistakes on every single commit

2023-01-23 08:46 UTC, antonispoulakis requested changes

2023-01-23 08:46 UTC, antonispoulakis commented on src/view/components/Auth.jsx
> +      dispatch(setLoading(false))
we've discussed this before. There is no point of you settings `loading` to true and then `false` here. `dispatch(setUser(currentUser))` is not an async call so the `setLoading` will just execute immediately one after another.

2023-01-24 07:58 UTC, antonispoulakis requested changes

2023-01-24 09:15 UTC, antonispoulakis approved these changes

2023-01-24 09:15 UTC, merged